global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'streamlit_dashboard'
    static_configs:
      - targets: ['streamlit_dashboard:8501'] # Assuming Streamlit exposes metrics
