# Configuration file for the project
alpha_vantage:
  api_key: "REPLACE_WITH_ACTUAL_KEY"  # Placeholder; actual key comes from secrets.yaml or environment variable
kafka:
  bootstrap_servers: "localhost:9092"
spark:
  master: "local[*]"
mlflow:
  tracking_uri: "http://localhost:5000"