# Configuration file for the project
openai:
  api_key: "${OPENAI_API_KEY}"  

finnhub:
  api_key: "${FINNHUB_API_KEY}"  

kafka:
  bootstrap_servers: "localhost:9092"

spark:
  master: "local[*]"

mlflow:
  tracking_uri: "http://localhost:5000"
